
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.br.edu.utfpr.pb=DEBUG

spring.application.name=server
server.port=8080

# PostgreSQL
# spring.jpa.database=postgresql
# spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/pw44s
# spring.datasource.username=postgres
# spring.datasource.password=2006

# H2 Database
spring.datasource.url=jdbc:h2:mem:pw44s
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=malagegustavo@gmail.com
spring.mail.password=zbtwnxypgqxojski

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


minio.endpoint=http://localhost
minio.port=9000
minio.access-key=minio@admin
minio.secret-key=minio@admin
minio.bucket-name=commons