logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.br.edu.utfpr.pb=DEBUG

spring.application.name=server
server.port=8080

spring.datasource.url=jdbc:h2:mem:pw44s;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/dev
spring.flyway.clean-disabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=malagegustavo@gmail.com
spring.mail.password=zbtwnxypgqxojski
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

minio.endpoint=http://localhost
minio.port=9000
minio.access-key=minio@admin
minio.secret-key=minio@admin
minio.bucket-name=commons

