CREATE TABLE tb_category (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(255)
);


CREATE TABLE tb_user (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username VARCHAR(255) NOT NULL,
                         display_name VARCHAR(255) NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         email VARCHAR(255) NOT NULL,
                         active BOOLEAN NOT NULL
);

CREATE TABLE tb_authority (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              authority VARCHAR(255)
);

CREATE TABLE tb_user_authorities (
                                     user_id BIGINT NOT NULL,
                                     authority_id BIGINT NOT NULL,
                                     PRIMARY KEY (user_id, authority_id),
                                     CONSTRAINT fk_user_authorities_user FOREIGN KEY (user_id) REFERENCES tb_user (id),
                                     CONSTRAINT fk_user_authorities_authority FOREIGN KEY (authority_id) REFERENCES tb_authority (id)
);

CREATE TABLE tb_address (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id BIGINT,
                            street VARCHAR(255),
                            complement VARCHAR(255),
                            city VARCHAR(255),
                            state VARCHAR(255),
                            house_number VARCHAR(255),
                            zip VARCHAR(255),
                            CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES tb_user (id)
);

CREATE TABLE tb_product (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255),
                            description VARCHAR(255),
                            price NUMERIC(38, 2),
                            url_image VARCHAR(4000),
                            long_description VARCHAR(4000),
                            autor_name VARCHAR(255),
                            category_id BIGINT,
                            CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES tb_category (id)
);


CREATE TABLE tb_order (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          date_order TIMESTAMP,
                          total_price NUMERIC(38, 2),
                          user_id BIGINT,
                          payment_type VARCHAR(255),
                          shipping_type VARCHAR(255),
                          shipping NUMERIC(38, 2),
                          address_id BIGINT,
                          order_status VARCHAR(255),
                          image_name VARCHAR(255),
                          content_type VARCHAR(255),
                          CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES tb_user (id)
);

CREATE TABLE tb_order_item (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               unit_price NUMERIC(38, 2) NOT NULL,
                               quantity INT NOT NULL,
                               total_price_items NUMERIC(38, 2),
                               order_id BIGINT,
                               product_id BIGINT,
                               url_image VARCHAR(4000),
                               CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES tb_order (id),
                               CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES tb_product (id)
);