version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minio@admin"
      MINIO_ROOT_PASSWORD: "minio@admin"
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  minio-config:
    image: minio/mc:latest
    container_name: minio_config
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set meu_minio http://minio:9000 minio@admin minio@admin) do echo 'Aguardando MinIO...' && sleep 1; done;
      /usr/bin/mc mb meu_minio/commons || true;
      /usr/bin/mc anonymous set download meu_minio/commons || true;
      echo '=== BUCKET COMMONS CONFIGURADO COMO PUBLICO VIA MC ===';
      exit 0;
      "

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build: ./filebeat
    container_name: filebeat
    volumes:
      - ./logs:/usr/share/filebeat/logs:rw
    depends_on:
      - elasticsearch

volumes:
  es_data: