filebeat.inputs:
  - type: filestream    
    id: spring-logs-stream
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.json
      - /usr/share/filebeat/logs/*.log
    parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true
          add_error_key: true
          message_key: message

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "spring-api-logs-%{+yyyy.MM.dd}"

setup.template.name: "spring-api-logs"
setup.template.pattern: "spring-api-logs-*"

setup.kibana:
  host: "http://kibana:5601"